DROP TABLE IF EXISTS `aarau1.t_partitioned`;
CREATE EXTERNAL TABLE `aarau1.t_partitioned`(
  `hit_time_gmt` bigint, 
  `service` string, 
  `accept_language` string, 
  `date_time` string, 
  `visid_high` string, 
  `visid_low` string, 
  `event_list` string, 
  `homepage` string, 
  `ip` string, 
  `page_event` int, 
  `page_event_var1` string, 
  `page_event_var2` string, 
  `page_type` string, 
  `page_url` string, 
  `pagename` string, 
  `product_list` string, 
  `user_server` string, 
  `prop1` string, 
  `prop2` string, 
  `prop3` string, 
  `prop4` string, 
  `prop5` string, 
  `prop6` string, 
  `prop7` string, 
  `prop8` string, 
  `prop9` string, 
  `prop10` string, 
  `prop11` string, 
  `prop12` string, 
  `prop13` string, 
  `prop14` string, 
  `prop15` string, 
  `prop16` string, 
  `prop17` string, 
  `prop18` string, 
  `prop19` string, 
  `prop20` string, 
  `prop21` string, 
  `prop22` string, 
  `prop23` string, 
  `prop24` string, 
  `prop25` string, 
  `prop26` string, 
  `prop27` string, 
  `prop28` string, 
  `prop29` string, 
  `prop30` string, 
  `prop31` string, 
  `prop32` string, 
  `prop33` string, 
  `prop34` string, 
  `prop35` string, 
  `prop36` string, 
  `prop37` string, 
  `prop38` string, 
  `prop39` string, 
  `prop40` string, 
  `prop41` string, 
  `prop42` string, 
  `prop43` string, 
  `prop44` string, 
  `prop45` string, 
  `prop46` string, 
  `prop47` string, 
  `prop48` string, 
  `prop49` string, 
  `prop50` string, 
  `purchaseid` string, 
  `referrer` string, 
  `state` string, 
  `user_agent` string, 
  `zip` string, 
  `search_engine` string, 
  `exclude_hit` int, 
  `hier1` string, 
  `hier2` string, 
  `hier3` string, 
  `hier4` string, 
  `hier5` string, 
  `browser` string, 
  `post_browser_height` int, 
  `post_browser_width` int, 
  `post_cookies` string, 
  `post_java_enabled` string, 
  `post_persistent_cookie` string, 
  `color` int, 
  `connection_type` int, 
  `country` int, 
  `domain` string, 
  `post_t_time_info` string, 
  `javascript` string, 
  `language` string, 
  `os` string, 
  `plugins` string, 
  `resolution` string, 
  `last_hit_time_gmt` bigint, 
  `first_hit_time_gmt` bigint, 
  `visit_start_time_gmt` bigint, 
  `last_purchase_time_gmt` string, 
  `last_purchase_num` int, 
  `first_hit_page_url` string, 
  `first_hit_pagename` string, 
  `visit_start_page_url` string, 
  `visit_start_pagename` string, 
  `first_hit_referrer` string, 
  `visit_referrer` string, 
  `visit_search_engine` int, 
  `visit_num` int, 
  `visit_page_num` int, 
  `prev_page` string, 
  `geo_city` string, 
  `geo_country` string, 
  `geo_region` string, 
  `duplicate_purchase` int, 
  `new_visit` int, 
  `daily_visitor` int, 
  `hourly_visitor` int, 
  `monthly_visitor` int, 
  `yearly_visitor` string, 
  `post_campaign` string, 
  `evar1` string, 
  `evar2` string, 
  `evar3` string, 
  `evar4` string, 
  `evar5` string, 
  `evar6` string, 
  `evar7` string, 
  `evar8` string, 
  `evar9` string, 
  `evar10` string, 
  `evar11` string, 
  `evar12` string, 
  `evar13` string, 
  `evar14` string, 
  `evar15` string, 
  `evar16` string, 
  `evar17` string, 
  `evar18` string, 
  `evar19` string, 
  `evar20` string, 
  `evar21` string, 
  `evar22` string, 
  `evar23` string, 
  `evar24` string, 
  `evar25` string, 
  `evar26` string, 
  `evar27` string, 
  `evar28` string, 
  `evar29` string, 
  `evar30` string, 
  `evar31` string, 
  `evar32` string, 
  `evar33` string, 
  `evar34` string, 
  `evar35` string, 
  `evar36` string, 
  `evar37` string, 
  `evar38` string, 
  `evar39` string, 
  `evar40` string, 
  `evar41` string, 
  `evar42` string, 
  `evar43` string, 
  `evar44` string, 
  `evar45` string, 
  `evar46` string, 
  `evar47` string, 
  `evar48` string, 
  `evar49` string, 
  `evar50` string, 
  `post_evar1` string, 
  `post_evar2` string, 
  `post_evar3` string, 
  `post_evar4` string, 
  `post_evar5` string, 
  `post_evar6` string, 
  `post_evar7` string, 
  `post_evar8` string, 
  `post_evar9` string, 
  `post_evar10` string, 
  `post_evar11` string, 
  `post_evar12` string, 
  `post_evar13` string, 
  `post_evar14` string, 
  `post_evar15` string, 
  `post_evar16` string, 
  `post_evar17` string, 
  `post_evar18` string, 
  `post_evar19` string, 
  `post_evar20` string, 
  `post_evar21` string, 
  `post_evar22` string, 
  `post_evar23` string, 
  `post_evar24` string, 
  `post_evar25` string, 
  `post_evar26` string, 
  `post_evar27` string, 
  `post_evar28` string, 
  `post_evar29` string, 
  `post_evar30` string, 
  `post_evar31` string, 
  `post_evar32` string, 
  `post_evar33` string, 
  `post_evar34` string, 
  `post_evar35` string, 
  `post_evar36` string, 
  `post_evar37` string, 
  `post_evar38` string, 
  `post_evar39` string, 
  `post_evar40` string, 
  `post_evar41` string, 
  `post_evar42` string, 
  `post_evar43` string, 
  `post_evar44` string, 
  `post_evar45` string, 
  `post_evar46` string, 
  `post_evar47` string, 
  `post_evar48` string, 
  `post_evar49` string, 
  `post_evar50` string, 
  `click_action` string, 
  `click_action_type` string, 
  `click_context` string, 
  `click_context_type` string, 
  `click_sourceid` string, 
  `click_tag` string, 
  `user_hash` string, 
  `username` string, 
  `userid` string, 
  `hitid_high` string, 
  `hitid_low` string, 
  `browser_height` int, 
  `browser_width` int, 
  `c_color` string, 
  `code_ver` string, 
  `cookies` string, 
  `ct_connect_type` string, 
  `campaign` string, 
  `j_jscript` string, 
  `java_enabled` string, 
  `p_plugins` string, 
  `persistent_cookie` string, 
  `s_resolution` string, 
  `secondary_hit` int, 
  `stats_server` string, 
  `t_time_info` string, 
  `ua_color` string, 
  `ua_os` string, 
  `ua_pixels` string, 
  `currency` string, 
  `curr_rate` string, 
  `curr_factor` int, 
  `sampled_hit` string, 
  `truncated_hit` string, 
  `geo_dma` string, 
  `duplicate_events` string, 
  `weekly_visitor` int, 
  `quarterly_visitor` int, 
  `post_search_engine` string, 
  `paid_search` int, 
  `search_page_num` int, 
  `post_keywords` string, 
  `cust_hit_time_gmt` string, 
  `post_cust_hit_time_gmt` int, 
  `ip2` string, 
  `cust_visid` string, 
  `post_cust_visid` string, 
  `transactionid` string, 
  `hit_source` int, 
  `sourceid` string, 
  `post_visid_high` string, 
  `post_visid_low` string, 
  `namespace` string, 
  `duplicated_from` string, 
  `partner_plugins` string, 
  `visid_type` string, 
  `visid_new` string, 
  `visid_timestamp` bigint, 
  `product_merchandising` string, 
  `post_visid_type` string, 
  `page_event_var3` int, 
  `mobile_id` int, 
  `tnt` string, 
  `mvvar1` string, 
  `mvvar2` string, 
  `mvvar3` string, 
  `post_survey` string, 
  `post_tnt` string, 
  `post_mvvar1` string, 
  `post_mvvar2` string, 
  `post_mvvar3` string, 
  `prop51` string, 
  `prop52` string, 
  `prop53` string, 
  `prop54` string, 
  `prop55` string, 
  `prop56` string, 
  `prop57` string, 
  `prop58` string, 
  `prop59` string, 
  `prop60` string, 
  `prop61` string, 
  `prop62` string, 
  `prop63` string, 
  `prop64` string, 
  `prop65` string, 
  `prop66` string, 
  `prop67` string, 
  `prop68` string, 
  `prop69` string, 
  `prop70` string, 
  `prop71` string, 
  `prop72` string, 
  `prop73` string, 
  `prop74` string, 
  `prop75` string, 
  `post_prop51` string, 
  `post_prop52` string, 
  `post_prop53` string, 
  `post_prop54` string, 
  `post_prop55` string, 
  `post_prop56` string, 
  `post_prop57` string, 
  `post_prop58` string, 
  `post_prop59` string, 
  `post_prop60` string, 
  `post_prop61` string, 
  `post_prop62` string, 
  `post_prop63` string, 
  `post_prop64` string, 
  `post_prop65` string, 
  `post_prop66` string, 
  `post_prop67` string, 
  `post_prop68` string, 
  `post_prop69` string, 
  `post_prop70` string, 
  `post_prop71` string, 
  `post_prop72` string, 
  `post_prop73` string, 
  `post_prop74` string, 
  `post_prop75` string, 
  `evar51` string, 
  `evar52` string, 
  `evar53` string, 
  `evar54` string, 
  `evar55` string, 
  `evar56` string, 
  `evar57` string, 
  `evar58` string, 
  `evar59` string, 
  `evar60` string, 
  `evar61` string, 
  `evar62` string, 
  `evar63` string, 
  `evar64` string, 
  `evar65` string, 
  `evar66` string, 
  `evar67` string, 
  `evar68` string, 
  `evar69` string, 
  `evar70` string, 
  `evar71` string, 
  `evar72` string, 
  `evar73` string, 
  `evar74` string, 
  `evar75` string, 
  `post_evar51` string, 
  `post_evar52` string, 
  `post_evar53` string, 
  `post_evar54` string, 
  `post_evar55` string, 
  `post_evar56` string, 
  `post_evar57` string, 
  `post_evar58` string, 
  `post_evar59` string, 
  `post_evar60` string, 
  `post_evar61` string, 
  `post_evar62` string, 
  `post_evar63` string, 
  `post_evar64` string, 
  `post_evar65` string, 
  `post_evar66` string, 
  `post_evar67` string, 
  `post_evar68` string, 
  `post_evar69` string, 
  `post_evar70` string, 
  `post_evar71` string, 
  `post_evar72` string, 
  `post_evar73` string, 
  `post_evar74` string, 
  `post_evar75` string, 
  `ref_type` string, 
  `ref_domain` string, 
  `va_finder_id` int, 
  `va_finder_detail` string, 
  `va_closer_id` int, 
  `va_closer_detail` string, 
  `geo_zip` string, 
  `post_zip` string, 
  `post_channel` string, 
  `post_currency` string, 
  `post_event_list` string, 
  `post_hier1` string, 
  `post_hier2` string, 
  `post_hier3` string, 
  `post_hier4` string, 
  `post_hier5` string, 
  `post_page_event` int, 
  `post_page_event_var1` string, 
  `post_page_event_var2` string, 
  `post_page_event_var3` string, 
  `post_page_type` string, 
  `post_page_url` string, 
  `post_pagename_no_url` string, 
  `post_pagename` string, 
  `post_partner_plugins` string, 
  `post_product_list` string, 
  `post_prop1` string, 
  `post_prop2` string, 
  `post_prop3` string, 
  `post_prop4` string, 
  `post_prop5` string, 
  `post_prop6` string, 
  `post_prop7` string, 
  `post_prop8` string, 
  `post_prop9` string, 
  `post_prop10` string, 
  `post_prop11` string, 
  `post_prop12` string, 
  `post_prop13` string, 
  `post_prop14` string, 
  `post_prop15` string, 
  `post_prop16` string, 
  `post_prop17` string, 
  `post_prop18` string, 
  `post_prop19` string, 
  `post_prop20` string, 
  `post_prop21` string, 
  `post_prop22` string, 
  `post_prop23` string, 
  `post_prop24` string, 
  `post_prop25` string, 
  `post_prop26` string, 
  `post_prop27` string, 
  `post_prop28` string, 
  `post_prop29` string, 
  `post_prop30` string, 
  `post_prop31` string, 
  `post_prop32` string, 
  `post_prop33` string, 
  `post_prop34` string, 
  `post_prop35` string, 
  `post_prop36` string, 
  `post_prop37` string, 
  `post_prop38` string, 
  `post_prop39` string, 
  `post_prop40` string, 
  `post_prop41` string, 
  `post_prop42` string, 
  `post_prop43` string, 
  `post_prop44` string, 
  `post_prop45` string, 
  `post_prop46` string, 
  `post_prop47` string, 
  `post_prop48` string, 
  `post_prop49` string, 
  `post_prop50` string, 
  `post_purchaseid` string, 
  `post_referrer` string, 
  `post_state` string, 
  `tnt_post_vista` string, 
  `post_transactionid` string, 
  `va_instance_event` string, 
  `va_new_engagement` string, 
  `visit_keywords` string, 
  `report_dt_dim_id` int, 
  `hit_datetime` string, 
  `post_visitor_id_concat_string` string, 
  `report_suite_name` string, 
  `create_datetime` string, 
  `is_valid_bot` int, 
  `uid` string,
  `pt_date` string)
PARTITIONED BY (
  `channel` string)
STORED AS PARQUET
LOCATION
  'hdfs://nameservice1/user/aarau1/input/t_partitioned'
;

SET mapreduce.map.memory.mb=5120 ;
SET mapreduce.reduce.memory.mb=5120 ;
SET mapreduce.map.java.opts=-Xmx4608m ;
SET mapreduce.reduce.java.opts=-Xmx4608m;
SET hive.exec.dynamic.partition.mode=nonstrict;
SET hive.exec.dynamic.partition=true;

set mapreduce.job.reduces=100;
set hive.merge.mapfiles = false;
set hive.merge.mapredfiles = false;

insert into table `aarau1.t_partitioned`
partition (channel)
select
  hit_time_gmt,
  service,
  accept_language,
  date_time,
  visid_high,
  visid_low,
  event_list,
  homepage,
  ip,
  page_event,
  page_event_var1,
  page_event_var2,
  page_type,
  page_url,
  pagename,
  product_list,
  user_server,
  prop1,
  prop2,
  prop3,
  prop4,
  prop5,
  prop6,
  prop7,
  prop8,
  prop9,
  prop10,
  prop11,
  prop12,
  prop13,
  prop14,
  prop15,
  prop16,
  prop17,
  prop18,
  prop19,
  prop20,
  prop21,
  prop22,
  prop23,
  prop24,
  prop25,
  prop26,
  prop27,
  prop28,
  prop29,
  prop30,
  prop31,
  prop32,
  prop33,
  prop34,
  prop35,
  prop36,
  prop37,
  prop38,
  prop39,
  prop40,
  prop41,
  prop42,
  prop43,
  prop44,
  prop45,
  prop46,
  prop47,
  prop48,
  prop49,
  prop50,
  purchaseid,
  referrer,
  state,
  user_agent,
  zip,
  search_engine,
  exclude_hit,
  hier1,
  hier2,
  hier3,
  hier4,
  hier5,
  browser,
  post_browser_height,
  post_browser_width,
  post_cookies,
  post_java_enabled,
  post_persistent_cookie,
  color,
  connection_type,
  country,
  domain,
  post_t_time_info,
  javascript,
  language,
  os,
  plugins,
  resolution,
  last_hit_time_gmt,
  first_hit_time_gmt,
  visit_start_time_gmt,
  last_purchase_time_gmt,
  last_purchase_num,
  first_hit_page_url,
  first_hit_pagename,
  visit_start_page_url,
  visit_start_pagename,
  first_hit_referrer,
  visit_referrer,
  visit_search_engine,
  visit_num,
  visit_page_num,
  prev_page,
  geo_city,
  geo_country,
  geo_region,
  duplicate_purchase,
  new_visit,
  daily_visitor,
  hourly_visitor,
  monthly_visitor,
  yearly_visitor,
  post_campaign,
  evar1,
  evar2,
  evar3,
  evar4,
  evar5,
  evar6,
  evar7,
  evar8,
  evar9,
  evar10,
  evar11,
  evar12,
  evar13,
  evar14,
  evar15,
  evar16,
  evar17,
  evar18,
  evar19,
  evar20,
  evar21,
  evar22,
  evar23,
  evar24,
  evar25,
  evar26,
  evar27,
  evar28,
  evar29,
  evar30,
  evar31,
  evar32,
  evar33,
  evar34,
  evar35,
  evar36,
  evar37,
  evar38,
  evar39,
  evar40,
  evar41,
  evar42,
  evar43,
  evar44,
  evar45,
  evar46,
  evar47,
  evar48,
  evar49,
  evar50,
  post_evar1,
  post_evar2,
  post_evar3,
  post_evar4,
  post_evar5,
  post_evar6,
  post_evar7,
  post_evar8,
  post_evar9,
  post_evar10,
  post_evar11,
  post_evar12,
  post_evar13,
  post_evar14,
  post_evar15,
  post_evar16,
  post_evar17,
  post_evar18,
  post_evar19,
  post_evar20,
  post_evar21,
  post_evar22,
  post_evar23,
  post_evar24,
  post_evar25,
  post_evar26,
  post_evar27,
  post_evar28,
  post_evar29,
  post_evar30,
  post_evar31,
  post_evar32,
  post_evar33,
  post_evar34,
  post_evar35,
  post_evar36,
  post_evar37,
  post_evar38,
  post_evar39,
  post_evar40,
  post_evar41,
  post_evar42,
  post_evar43,
  post_evar44,
  post_evar45,
  post_evar46,
  post_evar47,
  post_evar48,
  post_evar49,
  post_evar50,
  click_action,
  click_action_type,
  click_context,
  click_context_type,
  click_sourceid,
  click_tag,
  user_hash,
  username,
  userid,
  hitid_high,
  hitid_low,
  browser_height,
  browser_width,
  c_color,
  code_ver,
  cookies,
  ct_connect_type,
  campaign,
  j_jscript,
  java_enabled,
  p_plugins,
  persistent_cookie,
  s_resolution,
  secondary_hit,
  stats_server,
  t_time_info,
  ua_color,
  ua_os,
  ua_pixels,
  currency,
  curr_rate,
  curr_factor,
  sampled_hit,
  truncated_hit,
  geo_dma,
  duplicate_events,
  weekly_visitor,
  quarterly_visitor,
  post_search_engine,
  paid_search,
  search_page_num,
  post_keywords,
  cust_hit_time_gmt,
  post_cust_hit_time_gmt,
  ip2,
  cust_visid,
  post_cust_visid,
  transactionid,
  hit_source,
  sourceid,
  post_visid_high,
  post_visid_low,
  namespace,
  duplicated_from,
  partner_plugins,
  visid_type,
  visid_new,
  visid_timestamp,
  product_merchandising,
  post_visid_type,
  page_event_var3,
  mobile_id,
  tnt,
  mvvar1,
  mvvar2,
  mvvar3,
  post_survey,
  post_tnt,
  post_mvvar1,
  post_mvvar2,
  post_mvvar3,
  prop51,
  prop52,
  prop53,
  prop54,
  prop55,
  prop56,
  prop57,
  prop58,
  prop59,
  prop60,
  prop61,
  prop62,
  prop63,
  prop64,
  prop65,
  prop66,
  prop67,
  prop68,
  prop69,
  prop70,
  prop71,
  prop72,
  prop73,
  prop74,
  prop75,
  post_prop51,
  post_prop52,
  post_prop53,
  post_prop54,
  post_prop55,
  post_prop56,
  post_prop57,
  post_prop58,
  post_prop59,
  post_prop60,
  post_prop61,
  post_prop62,
  post_prop63,
  post_prop64,
  post_prop65,
  post_prop66,
  post_prop67,
  post_prop68,
  post_prop69,
  post_prop70,
  post_prop71,
  post_prop72,
  post_prop73,
  post_prop74,
  post_prop75,
  evar51,
  evar52,
  evar53,
  evar54,
  evar55,
  evar56,
  evar57,
  evar58,
  evar59,
  evar60,
  evar61,
  evar62,
  evar63,
  evar64,
  evar65,
  evar66,
  evar67,
  evar68,
  evar69,
  evar70,
  evar71,
  evar72,
  evar73,
  evar74,
  evar75,
  post_evar51,
  post_evar52,
  post_evar53,
  post_evar54,
  post_evar55,
  post_evar56,
  post_evar57,
  post_evar58,
  post_evar59,
  post_evar60,
  post_evar61,
  post_evar62,
  post_evar63,
  post_evar64,
  post_evar65,
  post_evar66,
  post_evar67,
  post_evar68,
  post_evar69,
  post_evar70,
  post_evar71,
  post_evar72,
  post_evar73,
  post_evar74,
  post_evar75,
  ref_type,
  ref_domain,
  va_finder_id,
  va_finder_detail,
  va_closer_id,
  va_closer_detail,
  geo_zip,
  post_zip,
  post_channel,
  post_currency,
  post_event_list,
  post_hier1,
  post_hier2,
  post_hier3,
  post_hier4,
  post_hier5,
  post_page_event,
  post_page_event_var1,
  post_page_event_var2,
  post_page_event_var3,
  post_page_type,
  post_page_url,
  post_pagename_no_url,
  post_pagename,
  post_partner_plugins,
  post_product_list,
  post_prop1,
  post_prop2,
  post_prop3,
  post_prop4,
  post_prop5,
  post_prop6,
  post_prop7,
  post_prop8,
  post_prop9,
  post_prop10,
  post_prop11,
  post_prop12,
  post_prop13,
  post_prop14,
  post_prop15,
  post_prop16,
  post_prop17,
  post_prop18,
  post_prop19,
  post_prop20,
  post_prop21,
  post_prop22,
  post_prop23,
  post_prop24,
  post_prop25,
  post_prop26,
  post_prop27,
  post_prop28,
  post_prop29,
  post_prop30,
  post_prop31,
  post_prop32,
  post_prop33,
  post_prop34,
  post_prop35,
  post_prop36,
  post_prop37,
  post_prop38,
  post_prop39,
  post_prop40,
  post_prop41,
  post_prop42,
  post_prop43,
  post_prop44,
  post_prop45,
  post_prop46,
  post_prop47,
  post_prop48,
  post_prop49,
  post_prop50,
  post_purchaseid,
  post_referrer,
  post_state,
  tnt_post_vista,
  post_transactionid,
  va_instance_event,
  va_new_engagement,
  visit_keywords,
  report_dt_dim_id,
  hit_datetime,
  post_visitor_id_concat_string,
  report_suite_name,
  create_datetime,
  is_valid_bot,
  uid,
  pt_date,
  channel
from aarau1.t_input_text
distribute by rand()
;

show partitions `aarau1.t_partitioned`;
